In [1]:
import fuzzymatcher
import pandas as pd

In [2]:
cps_df = pd.read_csv('clean_data/cellphones.csv')
tgdd_df = pd.read_csv('clean_data/tgdd.csv')
tiki_df = pd.read_csv('clean_data/tiki.csv')
vt_df = pd.read_csv('clean_data/viettel.csv')
ddv_df = pd.read_csv('clean_data/didongviet.csv')

cps_df['id'] = cps_df.index
tgdd_df['id'] = tgdd_df.index
tiki_df['id'] = tiki_df.index
vt_df['id'] = vt_df.index
ddv_df['id'] = ddv_df.index

cps_df['src'] = 'CellphoneS'
tgdd_df['src'] = 'Thế giới di động'
tiki_df['src'] = 'Tiki'
vt_df['src'] = 'Viettel'
ddv_df['src'] = 'Di động Việt'

In [3]:
print(len(cps_df) + len(tgdd_df) + len(tiki_df) + len(vt_df) + len(ddv_df))

778

In [4]:
def get_brand(s):
    s = s.lower()
    if 'iphone' in s:
        return 'apple'
    elif 'samsung' in s:
        return 'samsung'
    elif 'xiaomi' in s:
        return 'xiaomi'
    elif 'oppo' in s:
        return 'oppo'
    else:
        return 'other'

In [5]:
cps_df['thuong_hieu'] = cps_df['ten'].apply(get_brand)
tgdd_df['thuong_hieu'] = tgdd_df['ten'].apply(get_brand)
tiki_df['thuong_hieu'] = tiki_df['ten'].apply(get_brand)
vt_df['thuong_hieu'] = vt_df['ten'].apply(get_brand)
ddv_df['thuong_hieu'] = ddv_df['ten'].apply(get_brand)

In [6]:
apple_cps_df = cps_df[cps_df['thuong_hieu'] == 'apple']
ss_cps_df = cps_df[cps_df['thuong_hieu'] == 'samsung']
xiaomi_cps_df = cps_df[cps_df['thuong_hieu'] == 'xiaomi']
oppo_cps_df = cps_df[cps_df['thuong_hieu'] == 'oppo']
other_cps_df = cps_df[cps_df['thuong_hieu'] == 'other']

In [7]:
apple_tgdd_df = tgdd_df[tgdd_df['thuong_hieu'] == 'apple']
ss_tgdd_df = tgdd_df[tgdd_df['thuong_hieu'] == 'samsung']
xiaomi_tgdd_df = tgdd_df[tgdd_df['thuong_hieu'] == 'xiaomi']
oppo_tgdd_df = tgdd_df[tgdd_df['thuong_hieu'] == 'oppo']
other_tgdd_df = tgdd_df[tgdd_df['thuong_hieu'] == 'other']

In [8]:
apple_tiki_df = tiki_df[tiki_df['thuong_hieu'] == 'apple']
ss_tiki_df = tiki_df[tiki_df['thuong_hieu'] == 'samsung']
xiaomi_tiki_df = tiki_df[tiki_df['thuong_hieu'] == 'xiaomi']
oppo_tiki_df = tiki_df[tiki_df['thuong_hieu'] == 'oppo']
other_tiki_df = tiki_df[tiki_df['thuong_hieu'] == 'other']

In [9]:
apple_vt_df = vt_df[vt_df['thuong_hieu'] == 'apple']
ss_vt_df = vt_df[vt_df['thuong_hieu'] == 'samsung']
xiaomi_vt_df = vt_df[vt_df['thuong_hieu'] == 'xiaomi']
oppo_vt_df = vt_df[vt_df['thuong_hieu'] == 'oppo']
other_vt_df = vt_df[vt_df['thuong_hieu'] == 'other']

In [10]:
apple_ddv_df = ddv_df[ddv_df['thuong_hieu'] == 'apple']
ss_ddv_df = ddv_df[ddv_df['thuong_hieu'] == 'samsung']
xiaomi_ddv_df = ddv_df[ddv_df['thuong_hieu'] == 'xiaomi']
oppo_ddv_df = ddv_df[ddv_df['thuong_hieu'] == 'oppo']
other_ddv_df = ddv_df[ddv_df['thuong_hieu'] == 'other']

In [11]:
left_on = ["ten", "gia",  "ram", "bo_nho_trong", "kich_thuoc_man_hinh"]
right_on = ["ten", "gia",  "ram", "bo_nho_trong", "kich_thuoc_man_hinh"]

# Matching data Apple

## TGDD

In [12]:
apple_df = apple_tgdd_df
len(apple_df)

4

## CellphoneS

In [13]:
apple_matcher = fuzzymatcher.link_table(apple_df, apple_cps_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
apple_matcher = apple_matcher[apple_matcher['match_score'] > 0.2]
apple_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
0,2,76,0.220153,1,iPhone 12 Pro 256GB,iPhone 12 Pro 256GB,26290000,26000000,6,6,256.0,256.0,6.1,6.1
2,8,27,0.254952,1,iPhone 12 mini 64GB,iPhone 12 mini 64GB,18990000,15000000,4,4,64.0,64.0,5.4,5.4

In [14]:
values = apple_matcher['__id_right'].unique().tolist()
apple_cps_df = apple_cps_df.query("id not in @values")

apple_df = pd.concat([apple_df, apple_cps_df])
apple_df = apple_df.reset_index(drop=True)
apple_df['id'] = apple_df.index
print(len(apple_df))

42

## Viettel

In [15]:
apple_matcher = fuzzymatcher.link_table(apple_df, apple_vt_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
apple_matcher = apple_matcher[apple_matcher['match_score'] > 0.2]
apple_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
14,5,3,0.341481,1,iPhone 13 Pro Max 128GB,iPhone 13 Pro Max 128GB,29690000,29490000,6,6,128.0,128.0,6.7,6.7
55,14,4,0.357683,1,iPhone 13 Pro Max 256GB,iPhone 13 Pro Max 256GB,32190000,31990000,6,6,256.0,256.0,6.7,6.7
74,17,21,0.362497,1,iPhone 13 mini 128GB,iPhone 13 mini 128GB,18990000,18990000,4,4,128.0,128.0,5.4,5.4
94,21,17,0.262985,1,iPhone 13 Pro 256GB,iPhone 13 Pro 256GB,29950000,29690000,6,6,256.0,256.0,6.1,6.1
112,23,4,0.222198,1,iPhone 13 Pro Max 512GB,iPhone 13 Pro Max 256GB,37500000,31990000,6,6,256.0,256.0,6.7,6.7
113,24,10,0.311797,1,iPhone 13 Pro Max 1TB,iPhone 13 Pro Max 1TB,44000000,41790000,6,6,1024.0,1024.0,6.7,6.7
173,34,95,0.252596,1,iPhone 13 mini 256GB,iPhone 13 mini 256GB,19990000,21490000,4,4,256.0,256.0,5.4,5.4
199,39,93,0.217099,1,iPhone 13 Pro 1TB,iPhone 13 Pro 1TB,40000000,39490000,6,6,1024.0,1024.0,6.1,6.1

In [16]:
values = apple_matcher['__id_right'].unique().tolist()
apple_vt_df = apple_vt_df.query("id not in @values")

apple_df = pd.concat([apple_df, apple_vt_df])
apple_df = apple_df.reset_index(drop=True)
apple_df['id'] = apple_df.index
print(len(apple_df))

52

## Tiki

In [17]:
apple_matcher = fuzzymatcher.link_table(apple_df, apple_tiki_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
apple_matcher = apple_matcher[apple_matcher['match_score'] > 0.2]
apple_matcher

Empty DataFrame
Columns: [__id_left, __id_right, match_score, match_rank, ten_left, ten_right, gia_left, gia_right, ram_left, ram_right, bo_nho_trong_left, bo_nho_trong_right, kich_thuoc_man_hinh_left, kich_thuoc_man_hinh_right]
Index: []

In [18]:
values = apple_matcher['__id_right'].unique().tolist()
apple_tiki_df = apple_tiki_df.query("id not in @values")

apple_df = pd.concat([apple_df, apple_tiki_df])
apple_df = apple_df.reset_index(drop=True)
apple_df['id'] = apple_df.index
print(len(apple_df))

56

## Didongviet

In [19]:
apple_matcher = fuzzymatcher.link_table(apple_df, apple_ddv_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
apple_matcher = apple_matcher[apple_matcher['match_score'] > 0.2]
apple_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
47,5,4,0.258057,1,iPhone 13 Pro Max 128GB,iPhone 13 Pro Max 128GB,29690000,26990000,6,6.0,128.0,128.0,6.7,6.7
79,7,4,0.256353,1,iPhone 12 Pro Max 128GB,iPhone 13 Pro Max 128GB,27000000,26990000,6,6.0,128.0,128.0,6.7,6.7
87,12,105,0.213228,1,iPhone 13 128GB - Xanh la,iPhone 13 128GB Xanh la,22000000,19790000,0,4.0,128.0,128.0,6.1,6.1
92,14,5,0.213456,1,iPhone 13 Pro Max 256GB,iPhone 13 Pro Max 256GB,32190000,29990000,6,0.0,256.0,256.0,6.7,6.7
132,20,16,0.220504,1,iPhone 13 256GB - Xanh la,iPhone 13 256GB Xanh La,23950000,22990000,0,4.0,256.0,256.0,6.1,6.1
168,24,7,0.269796,1,iPhone 13 Pro Max 1TB,iPhone 13 Pro Max 1TB,44000000,41990000,6,0.0,1024.0,1024.0,6.7,6.7
259,36,8,0.254190,1,iPhone 12 Pro 512GB,iPhone 12 Pro 512GB,27500000,27400000,6,0.0,512.0,512.0,6.1,6.1
260,37,24,0.297133,1,iPhone 13 mini 512GB,iPhone 13 mini 512GB,23000000,21990000,4,4.0,512.0,512.0,5.4,5.4
261,37,22,0.223483,2,iPhone 13 mini 512GB,iPhone 13 mini 512GB Xanh la,23000000,21990000,4,4.0,512.0,512.0,5.4,5.4
292,39,17,0.239954,1,iPhone 13 Pro 1TB,iPhone 13 Pro 1TB,40000000,37990000,6,6.0,1024.0,1024.0,6.1,6.1

In [20]:
values = apple_matcher['__id_right'].unique().tolist()
apple_ddv_df = apple_ddv_df.query("id not in @values")

apple_df = pd.concat([apple_df, apple_ddv_df])
apple_df = apple_df.reset_index(drop=True)
apple_df['id'] = apple_df.index
print(len(apple_df))

77

# Matching data Samsung

## TGDD

In [21]:
ss_df = ss_tgdd_df
len(ss_df)

10

## CellphoneS

In [22]:
ss_matcher = fuzzymatcher.link_table(ss_df, ss_cps_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
ss_matcher = ss_matcher[ss_matcher['match_score'] > 0.2]
ss_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
0,0,112,0.218353,1,Samsung Galaxy Z Fold3 5G 256GB,Samsung Galaxy Z Fold2 5G,35990000,23000000,12,12,256.0,256.0,13.8,13.83
3,1,39,0.232312,1,Samsung Galaxy S22 Ultra 5G 128GB,Samsung Galaxy S21 Ultra 5G,30990000,20390000,8,12,128.0,128.0,6.8,6.80
15,5,24,0.240209,1,Samsung Galaxy Z Flip3 5G 128GB,Samsung Galaxy Z Flip3 5G,21990000,20790000,8,8,128.0,128.0,8.6,6.70
16,9,26,0.556323,1,Samsung Galaxy S21 FE 5G (6GB/128GB),Samsung Galaxy S21 FE 5G (6GB - 128GB),15990000,13300000,6,6,128.0,128.0,6.4,6.40
30,33,40,0.352305,1,Samsung Galaxy A03 3GB,Samsung Galaxy A03 (3GB - 32GB),2990000,2850000,3,3,32.0,32.0,6.5,6.50

In [23]:
values = ss_matcher['__id_right'].unique().tolist()
ss_cps_df = ss_cps_df.query("id not in @values")

ss_df = pd.concat([ss_df, ss_cps_df])
ss_df = ss_df.reset_index(drop=True)
ss_df['id'] = ss_df.index
print(len(ss_df))

45

## Viettel

In [24]:
ss_matcher = fuzzymatcher.link_table(ss_df, ss_vt_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
ss_matcher = ss_matcher[ss_matcher['match_score'] > 0.2]
ss_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
0,0,36,0.492826,1,Samsung Galaxy Z Fold3 5G 256GB,Samsung Galaxy Z Fold3 5G 256GB,35990000,31990000,12,12,256.0,256.0,13.80,13.80
1,1,61,0.262921,1,Samsung Galaxy S22 Ultra 5G 128GB,Samsung Galaxy S21 Ultra 5G 12/128GB,30990000,19990000,8,12,128.0,128.0,6.80,6.80
16,4,5,0.323014,1,Samsung Galaxy Z Flip3 5G 128GB,Samsung Galaxy Z Flip3 5G 128GB,21990000,17990000,8,8,128.0,128.0,8.60,6.70
17,5,107,0.508935,1,Samsung Galaxy S21 FE 5G (6GB/128GB),Samsung Galaxy S21 FE 5G 6/128GB,15990000,15990000,6,6,128.0,128.0,6.40,6.40
58,10,70,0.277948,1,Samsung Galaxy A52s 5G,Samsung Galaxy A52s 5G,7850000,7690000,8,8,128.0,128.0,6.50,6.50
89,12,60,0.236796,1,Samsung Galaxy S20 FE 256GB (Fan Edition),Samsung Galaxy S20 FE 256GB,11990000,10990000,8,8,256.0,256.0,6.50,6.50
158,18,67,0.254878,1,Samsung Galaxy S21 FE 8GB 128GB,Samsung Galaxy S21 FE 5G 8/128GB,13750000,12990000,8,8,128.0,128.0,6.40,6.40
167,20,59,0.235752,1,Samsung Galaxy A22 4G,Samsung Galaxy A32 4G,4700000,5690000,6,6,128.0,128.0,6.40,6.40
251,26,71,0.377686,1,Samsung Galaxy S21 FE 5G (8GB - 256GB),Samsung Galaxy S21 FE 5G 8/256GB,15900000,13990000,8,8,256.0,256.0,6.40,6.40
252,27,37,0.347053,1,Samsung Galaxy Z Flip3 5G 256GB,Samsung Galaxy Z Flip3 5G 256GB,22590000,19990000,8,8,256.0,256.0,6.70,8.60
358,34,0,0.222750,1,Samsung Galaxy S21 Ultra 5G 256GB,Samsung Galaxy S22 Ultra 12/256GB,29800000,31990000,12,12,256.0,256.0,6.80,6.80
452,40,111,0.265520,1,Samsung Galaxy Z Fold2 5G (Phien ban mua xuan),Samsung Galaxy Z Fold 2 5G Phien ban mua he,23000000,50000000,12,12,256.0,256.0,13.83,13.82
453,41,111,0.563316,1,Samsung Galaxy Z Fold2 5G (Phien ban mua he),Samsung Galaxy Z Fold 2 5G Phien ban mua he,23000000,50000000,12,12,256.0,256.0,13.83,13.82

In [25]:
values = ss_matcher['__id_right'].unique().tolist()
ss_vt_df = ss_vt_df.query("id not in @values")

ss_df = pd.concat([ss_df, ss_vt_df])
ss_df = ss_df.reset_index(drop=True)
ss_df['id'] = ss_df.index
print(len(ss_df))

63

## Tiki

In [26]:
ss_matcher = fuzzymatcher.link_table(ss_df, ss_tiki_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
ss_matcher = ss_matcher[ss_matcher['match_score'] > 0.2]
ss_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
64,1,113,0.404282,1,Samsung Galaxy S22 Ultra 5G 128GB,Samsung Galaxy S22 Ultra 5G 8GB/128GB,30990000,24490000,8,8,128.0,128.0,6.8,6.8
68,3,133,0.312009,1,Samsung Galaxy S22 5G 128GB,Samsung Galaxy S22 5G (8GB/128GB ),21990000,16390000,8,8,128.0,128.0,6.1,6.1
139,6,192,0.215263,1,Samsung Galaxy A23 4GB,Samsung Galaxy A23 (4GB/128GB),5690000,4829000,4,4,128.0,128.0,6.6,6.6
140,7,52,0.211098,1,Samsung Galaxy A13 4GB,Samsung Galaxy A13 (4GB/128GB),4690000,3770000,4,4,128.0,128.0,6.6,6.6
141,7,169,0.211098,2,Samsung Galaxy A13 4GB,Samsung Galaxy A13 (4GB/128GB),4690000,3899000,4,4,128.0,128.0,6.6,6.6
142,8,24,0.209718,1,Samsung Galaxy A12 4GB (2021),Samsung Galaxy A12 6GB (2021),3490000,3890000,4,6,128.0,128.0,6.5,6.5
155,9,237,0.303460,1,Samsung Galaxy A03 3GB,Samsung Galaxy A03 32GB Xanh,2990000,2990000,3,3,32.0,32.0,6.5,6.5
156,9,242,0.297590,2,Samsung Galaxy A03 3GB,Samsung Galaxy A03 32GB Den,2990000,2990000,3,3,32.0,32.0,6.5,6.5
157,10,49,0.281326,1,Samsung Galaxy A52s 5G,Samsung Galaxy A52s 5G (8GB/128GB),7850000,7890000,8,8,128.0,128.0,6.5,6.5
225,12,130,0.212283,1,Samsung Galaxy S20 FE 256GB (Fan Edition),Samsung Galaxy S20 FE (8GB/256GB),11990000,11659000,8,8,256.0,256.0,6.5,6.5
393,18,70,0.339474,1,Samsung Galaxy S21 FE 8GB 128GB,Samsung Galaxy S21 FE 5G (8GB/128GB),13750000,12990000,8,8,128.0,128.0,6.4,6.4
394,18,89,0.339474,2,Samsung Galaxy S21 FE 8GB 128GB,Samsung Galaxy S21 FE 5G 8GB/128GB,13750000,12879000,8,8,128.0,128.0,6.4,6.4
395,18,122,0.339474,3,Samsung Galaxy S21 FE 8GB 128GB,Samsung Galaxy S21 FE 5G (8GB/128GB),13750000,12989000,8,8,128.0,128.0,6.4,6.4
432,22,65,0.365110,1,Samsung Galaxy Note 20 Ultra,Samsung Galaxy Note 20 Ultra (8GB/256GB),19200000,20090000,8,8,256.0,256.0,6.9,6.9
524,25,102,0.209098,1,Samsung Galaxy A73 128GB,Samsung Galaxy A73 5G (8GB/128GB),11290000,9619000,8,8,128.0,128.0,6.7,6.7
525,25,144,0.209098,2,Samsung Galaxy A73 128GB,Samsung Galaxy A73 5G (8GB/128GB),11290000,9989000,8,8,128.0,128.0,6.7,6.7
526,26,168,0.484899,1,Samsung Galaxy S21 FE 5G (8GB - 256GB),Samsung Galaxy S21 FE 5G (8GB/256GB),15900000,15059000,8,8,256.0,256.0,6.4,6.4
899,34,129,0.430074,1,Samsung Galaxy S21 Ultra 5G 256GB,Samsung Galaxy S22 Ultra 5G (12GB/256GB),29800000,25390000,12,12,256.0,256.0,6.8,6.8
1429,46,132,0.232708,1,Samsung Galaxy S22 Plus 8/128GB,Samsung Galaxy S22 Plus 5G (8GB/128GB),23990000,21699000,8,8,128.0,128.0,6.6,6.6
1430,47,233,0.370688,1,Samsung Galaxy A33 5G (8/128GB),Samsung Galaxy A33 5G (8/128GB),7990000,8490000,8,8,128.0,128.0,6.4,6.4
1502,50,102,0.239104,1,Samsung Galaxy A73 5G (8/128GB),Samsung Galaxy A73 5G (8GB/128GB),10990000,9619000,8,8,128.0,128.0,6.7,6.7
1503,50,144,0.239104,2,Samsung Galaxy A73 5G (8/128GB),Samsung Galaxy A73 5G (8GB/128GB),10990000,9989000,8,8,128.0,128.0,6.7,6.7
1505,52,95,0.227695,1,Samsung Galaxy A33 5G (6/128GB),Samsung Galaxy A33 5G (6GB/128GB),7490000,6690000,6,6,128.0,128.0,6.4,6.4
1506,52,155,0.217661,2,Samsung Galaxy A33 5G (6/128GB),Samsung Galaxy A33 5G (6GB/128GB),7490000,6649000,6,6,128.0,128.0,6.4,6.4
1519,56,158,0.253728,1,Samsung Galaxy S22 Ultra 8/128GB,Samsung Galaxy S22 Ultra (8GB/128GB),28990000,25619000,8,8,128.0,128.0,6.8,6.8
1520,56,113,0.216869,2,Samsung Galaxy S22 Ultra 8/128GB,Samsung Galaxy S22 Ultra 5G 8GB/128GB,28990000,24490000,8,8,128.0,128.0,6.8,6.8

In [27]:
values = ss_matcher['__id_right'].unique().tolist()
ss_tiki_df = ss_tiki_df.query("id not in @values")

ss_df = pd.concat([ss_df, ss_tiki_df])
ss_df = ss_df.reset_index(drop=True)
ss_df['id'] = ss_df.index
print(len(ss_df))

115

## Didongviet

In [28]:
ss_matcher = fuzzymatcher.link_table(ss_df, ss_ddv_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
ss_matcher = ss_matcher[ss_matcher['match_score'] > 0.2]
ss_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
0,0,39,0.507607,1,Samsung Galaxy Z Fold3 5G 256GB,Samsung Galaxy Z Fold3 5G (12GB|256GB),35990000,29990000,12,12.0,256.0,256.0,13.8,13.8
1,1,29,0.382046,1,Samsung Galaxy S22 Ultra 5G 128GB,Samsung Galaxy S22 Ultra 5G (8GB|128GB),30990000,23390000,8,8.0,128.0,128.0,6.8,6.8
2,1,111,0.339938,2,Samsung Galaxy S22 Ultra 5G 128GB,Samsung Galaxy S22 Ultra 5G (8GB|128GB) (BHDT),30990000,22790000,8,8.0,128.0,128.0,6.8,6.8
8,3,25,0.302510,1,Samsung Galaxy S22 5G 128GB,Samsung Galaxy S22 5G (8GB|128GB),21990000,14990000,8,8.0,128.0,128.0,6.1,6.1
9,4,36,0.425334,1,Samsung Galaxy Z Flip3 5G 128GB,Samsung Galaxy Z Flip3 5G (8GB|128GB),21990000,16790000,8,8.0,128.0,128.0,8.6,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,106,114,0.200807,3,Samsung Galaxy S22 5G (8GB),Samsung Galaxy S22 5G (8GB|256GB) (BHDT),14660000,16690000,8,8.0,0.0,256.0,6.1,6.1
1310,108,101,0.208096,1,Samsung A23 4GB/128GB,Samsung Galaxy A23 (4GB|128GB),5050000,4790000,4,4.0,128.0,128.0,6.6,6.6
1316,110,42,0.214906,1,Samsung Galaxy A13 (6GB/128GB),Samsung Galaxy A22 (6GB|128GB),5190000,4390000,6,6.0,128.0,128.0,6.6,6.6
1320,111,118,0.227115,1,Samsung Galaxy A53 5G (8GB/128GB),Samsung Galaxy A53 (8GB|128GB),9690000,8090000,8,8.0,128.0,128.0,6.5,6.5
1325,112,79,0.292693,1,Samsung Galaxy A03s 64GB Den,Samsung Galaxy A03s (4GB|64GB),3690000,3390000,4,4.0,64.0,64.0,6.5,6.5

In [29]:
values = ss_matcher['__id_right'].unique().tolist()
ss_ddv_df = ss_ddv_df.query("id not in @values")

ss_df = pd.concat([ss_df, ss_ddv_df])
ss_df = ss_df.reset_index(drop=True)
ss_df['id'] = ss_df.index
print(len(ss_df))

124

# Matching data Xiaomi

## TGDD

In [30]:
xiaomi_df = xiaomi_tgdd_df
len(xiaomi_df)

9

## CellphoneS

In [31]:
xiaomi_matcher = fuzzymatcher.link_table(xiaomi_df, xiaomi_cps_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
xiaomi_matcher = xiaomi_matcher[xiaomi_matcher['match_score'] > 0.2]
xiaomi_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
36,19,41,0.201780,1,Xiaomi Redmi Note 10S 6GB,Xiaomi Redmi Note 10S,5990000,4990000,6,8,128.0,128.0,6.43,6.43
46,34,136,0.362153,1,Xiaomi Redmi 9C (3GB/64GB),Xiaomi Redmi 9C 3GB - 64GB,2990000,2890000,3,3,64.0,64.0,6.53,6.53

In [32]:
values = xiaomi_matcher['__id_right'].unique().tolist()
xiaomi_cps_df = xiaomi_cps_df.query("id not in @values")

xiaomi_df = pd.concat([xiaomi_df, xiaomi_cps_df])
xiaomi_df = xiaomi_df.reset_index(drop=True)
xiaomi_df['id'] = xiaomi_df.index
print(len(xiaomi_df))

40

## Viettel

In [33]:
xiaomi_matcher = fuzzymatcher.link_table(xiaomi_df, xiaomi_vt_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
xiaomi_matcher = xiaomi_matcher[xiaomi_matcher['match_score'] > 0.2]
xiaomi_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
0,0,103,0.225874,1,Xiaomi 12,Xiaomi 12 5G,19990000,19990000,8,8,256.0,256.0,6.28,6.28
21,2,26,0.287782,1,Xiaomi Redmi Note 11 Pro,Xiaomi Redmi Note 11 Pro,7190000,6790000,8,8,128.0,128.0,6.67,6.67
22,2,24,0.248171,2,Xiaomi Redmi Note 11 Pro,Xiaomi Redmi Note 11 Pro 5G,7190000,7990000,8,8,128.0,128.0,6.67,6.67
30,4,56,0.220935,1,Xiaomi Redmi Note 10S 6GB,Xiaomi Redmi Note 11S,5990000,5990000,6,8,128.0,128.0,6.43,6.43
49,6,51,0.386077,1,Xiaomi Redmi Note 11 (4GB/64GB),Xiaomi Redmi Note 11 4/64GB,4190000,4190000,4,4,64.0,64.0,6.43,6.43
53,8,69,0.368467,1,Xiaomi Redmi 9C (3GB/64GB),Xiaomi Redmi 9C 3/64GB,2990000,2990000,3,3,64.0,64.0,6.53,6.53
62,11,76,0.228741,1,Xiaomi Redmi 9A,Xiaomi Redmi 9A 2/32GB,2390000,2390000,2,2,32.0,32.0,6.53,6.53
63,12,80,0.204097,1,Xiaomi Redmi 10 (4GB - 64GB),Xiaomi Redmi 10 4/64GB,3650000,3490000,4,4,64.0,64.0,6.50,6.50
66,14,41,0.366762,1,Xiaomi Redmi 10C 4GB 128GB,Xiaomi Redmi 10C 4/128GB,3690000,3690000,4,4,128.0,128.0,6.71,6.71
134,19,49,0.343708,1,Xiaomi 11 Lite 5G NE,Xiaomi 11 Lite 5G NE 8/128GB,8000000,7690000,8,8,128.0,128.0,6.55,6.55
175,22,77,0.270173,1,Xiaomi Redmi Note 10 Pro 8GB,Xiaomi Redmi Note 10 Pro 8/128GB,6090000,6490000,8,8,128.0,128.0,6.67,6.67
275,29,77,0.200276,1,Xiaomi Redmi Note 10 Pro 6GB,Xiaomi Redmi Note 10 Pro 8/128GB,6900000,6490000,6,8,128.0,128.0,6.67,6.67

In [34]:
values = xiaomi_matcher['__id_right'].unique().tolist()
xiaomi_vt_df = xiaomi_vt_df.query("id not in @values")

xiaomi_df = pd.concat([xiaomi_df, xiaomi_vt_df])
xiaomi_df = xiaomi_df.reset_index(drop=True)
xiaomi_df['id'] = xiaomi_df.index
print(len(xiaomi_df))

49

## Tiki

In [35]:
xiaomi_matcher = fuzzymatcher.link_table(xiaomi_df, xiaomi_tiki_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
xiaomi_matcher = xiaomi_matcher[xiaomi_matcher['match_score'] > 0.2]
xiaomi_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
43,1,86,0.288593,1,Xiaomi 11T 5G 128GB,Xiaomi 11T (8GB/128GB),8990000,8990000,8,8,128.0,128.0,6.67,6.67
44,1,72,0.207631,2,Xiaomi 11T 5G 128GB,Xiaomi 11T (8G/128GB),8990000,9290000,8,8,128.0,128.0,6.67,6.67
51,2,16,0.205171,1,Xiaomi Redmi Note 11 Pro,Xiaomi Redmi Note 11 Pro (8GB/128GB),7190000,6699000,8,8,128.0,128.0,6.67,6.67
52,2,17,0.205171,2,Xiaomi Redmi Note 11 Pro,Xiaomi Redmi Note 11 Pro (8GB/128GB),7190000,6985000,8,8,128.0,128.0,6.67,6.67
76,6,40,0.474416,1,Xiaomi Redmi Note 11 (4GB/64GB),Xiaomi Redmi Note 11 (4GB/64GB),4190000,4190000,4,4,64.0,64.0,6.43,6.43
97,8,43,0.360805,1,Xiaomi Redmi 9C (3GB/64GB),Xiaomi Redmi 9C 3GB/64GB,2990000,2649000,3,3,64.0,64.0,6.53,6.53
98,8,101,0.360805,2,Xiaomi Redmi 9C (3GB/64GB),Xiaomi Redmi 9C 3GB/64GB,2990000,2639000,3,3,64.0,64.0,6.53,6.53
99,9,71,0.259914,1,Xiaomi Mi 11 Lite 5G,Xiaomi 11 Lite 5G NE (8GB/128GB),7490000,7490000,8,8,128.0,128.0,6.55,6.55
103,12,97,0.257414,1,Xiaomi Redmi 10 (4GB - 64GB),Xiaomi Redmi 10 4GB/128GB,3650000,3669000,4,4,64.0,128.0,6.50,6.50
209,16,53,0.256594,1,Xiaomi Redmi 10 (4GB - 128GB),Xiaomi Redmi 10 (4GB/128GB),4290000,3689000,4,4,128.0,128.0,6.50,6.50
210,16,97,0.256594,2,Xiaomi Redmi 10 (4GB - 128GB),Xiaomi Redmi 10 4GB/128GB,4290000,3669000,4,4,128.0,128.0,6.50,6.50
297,19,105,0.444329,1,Xiaomi 11 Lite 5G NE,Xiaomi 11 Lite 5G NE,8000000,8190000,8,8,128.0,128.0,6.55,6.55
298,19,71,0.378828,2,Xiaomi 11 Lite 5G NE,Xiaomi 11 Lite 5G NE (8GB/128GB),8000000,7490000,8,8,128.0,128.0,6.55,6.55
362,22,110,0.377818,1,Xiaomi Redmi Note 10 Pro 8GB,Xiaomi Redmi Note 10 Pro (8GB/128GB),6090000,7490000,8,8,128.0,128.0,6.67,6.67
516,29,110,0.246243,1,Xiaomi Redmi Note 10 Pro 6GB,Xiaomi Redmi Note 10 Pro (8GB/128GB),6900000,7490000,6,8,128.0,128.0,6.67,6.67
692,35,105,0.284467,1,Xiaomi 11 Lite 5G NE Trang Swarovski,Xiaomi 11 Lite 5G NE,9490000,8190000,8,8,128.0,128.0,6.55,6.55
693,35,71,0.218966,2,Xiaomi 11 Lite 5G NE Trang Swarovski,Xiaomi 11 Lite 5G NE (8GB/128GB),9490000,7490000,8,8,128.0,128.0,6.55,6.55
786,39,43,0.211966,1,Xiaomi Redmi Note 9 3G\r\n3GB - 64GB,Xiaomi Redmi 9C 3GB/64GB,3400000,2649000,3,3,64.0,64.0,6.53,6.53
787,39,101,0.211966,2,Xiaomi Redmi Note 9 3G\r\n3GB - 64GB,Xiaomi Redmi 9C 3GB/64GB,3400000,2639000,3,3,64.0,64.0,6.53,6.53
893,44,226,0.308748,1,Xiaomi Redmi Note 11 4/128GB,Xiaomi Redmi Note 11 (4GB/128GB),4490000,4490000,4,4,128.0,128.0,6.43,6.43
899,46,195,0.294451,1,Xiaomi Redmi 9C 4/128GB,Xiaomi Redmi 9C (4GB/128GB),3190000,3190000,4,4,128.0,128.0,6.53,6.53
900,47,85,0.334832,1,Xiaomi Redmi Note 10S 8/128GB,Xiaomi Redmi Note 11S (8GB/128GB),5690000,5690000,8,8,128.0,128.0,6.43,6.43

In [36]:
values = xiaomi_matcher['__id_right'].unique().tolist()
xiaomi_tiki_df = xiaomi_tiki_df.query("id not in @values")

xiaomi_df = pd.concat([xiaomi_df, xiaomi_tiki_df])
xiaomi_df = xiaomi_df.reset_index(drop=True)
xiaomi_df['id'] = xiaomi_df.index
print(len(xiaomi_df))

77

## Didongviet

In [37]:
xiaomi_matcher = fuzzymatcher.link_table(xiaomi_df, xiaomi_ddv_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
xiaomi_matcher = xiaomi_matcher[xiaomi_matcher['match_score'] > 0.2]
xiaomi_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
20,2,100,0.222252,1,Xiaomi Redmi Note 11 Pro,Xiaomi Redmi Note 11 Pro 5G (8GB|128GB),7190000,7590000,8,8.0,128.0,128.0,6.67,6.67
27,6,120,0.371667,1,Xiaomi Redmi Note 11 (4GB/64GB),Xiaomi Redmi Note 11 (4GB|64GB),4190000,4190000,4,4.0,64.0,0.0,6.43,6.43
40,10,70,0.270516,1,Xiaomi Redmi 10 4GB - 128GB (2022),Xiaomi Redmi 10 2022 (4GB|128GB),4290000,3690000,4,4.0,128.0,128.0,6.50,6.50
85,19,51,0.349061,1,Xiaomi 11 Lite 5G NE,Xiaomi 11 Lite 5G NE (8GB|128GB),8000000,7590000,8,8.0,128.0,128.0,6.55,6.55
106,22,100,0.229647,1,Xiaomi Redmi Note 10 Pro 8GB,Xiaomi Redmi Note 11 Pro 5G (8GB|128GB),6090000,7590000,8,8.0,128.0,128.0,6.67,6.67
288,47,115,0.323463,1,Xiaomi Redmi Note 10S 8/128GB,Xiaomi Redmi Note 11s (8GB|128GB),5690000,5690000,8,8.0,128.0,128.0,6.43,6.43
312,51,121,0.272812,1,Xiaomi Redmi Note 11 (4GB/128GB),Xiaomi Redmi Note 11 (4GB|128GB),4179000,4360000,4,4.0,128.0,128.0,6.43,6.43
313,52,121,0.272812,1,Xiaomi Redmi Note 11 4GB/128GB,Xiaomi Redmi Note 11 (4GB|128GB),4099000,4360000,4,4.0,128.0,128.0,6.43,6.43
314,53,120,0.242118,1,Xiaomi Redmi Note 11 (4GB/64GB),Xiaomi Redmi Note 11 (4GB|64GB),3919000,4190000,4,4.0,64.0,0.0,6.43,6.43
316,54,120,0.258022,1,Xiaomi Redmi Note 11 (4GB/64GB),Xiaomi Redmi Note 11 (4GB|64GB),3990000,4190000,4,4.0,64.0,0.0,6.43,6.43
328,56,115,0.373746,1,Xiaomi Redmi Note 11S (8GB/128GB),Xiaomi Redmi Note 11s (8GB|128GB),5829000,5690000,8,8.0,128.0,128.0,6.43,6.43
332,58,121,0.282846,1,Xiaomi Redmi Note 11 (4GB/128GB),Xiaomi Redmi Note 11 (4GB|128GB),4250000,4360000,4,4.0,128.0,128.0,6.43,6.43
339,62,100,0.518332,1,Xiaomi Redmi Note 11 Pro 5G 8GB/128GB,Xiaomi Redmi Note 11 Pro 5G (8GB|128GB),8009000,7590000,8,8.0,128.0,128.0,6.67,6.67
344,65,120,0.242118,1,Xiaomi Redmi Note 11 4GB/64GB,Xiaomi Redmi Note 11 (4GB|64GB),3890000,4190000,4,4.0,64.0,0.0,6.43,6.43
366,68,115,0.373746,1,Xiaomi Redmi Note 11S 8GB/128GB,Xiaomi Redmi Note 11s (8GB|128GB),5829000,5690000,8,8.0,128.0,128.0,6.43,6.43
367,69,100,0.518332,1,Xiaomi Redmi Note 11 Pro 5G (8GB/128GB),Xiaomi Redmi Note 11 Pro 5G (8GB|128GB),8080000,7590000,8,8.0,128.0,128.0,6.67,6.67
368,70,100,0.518332,1,Xiaomi Redmi Note 11 Pro 5G (8GB/128GB),Xiaomi Redmi Note 11 Pro 5G (8GB|128GB),8059000,7590000,8,8.0,128.0,128.0,6.67,6.67
369,71,137,0.335309,1,Xiaomi Redmi 9A (2GB/32GB),Xiaomi Redmi 9A (2GB|32GB),2070000,2200000,2,2.0,32.0,32.0,6.53,6.53
381,74,121,0.272812,1,Xiaomi Redmi Note 11 (4GB/128GB),Xiaomi Redmi Note 11 (4GB|128GB),4279000,4360000,4,4.0,128.0,128.0,6.43,6.43

In [38]:
values = xiaomi_matcher['__id_right'].unique().tolist()
xiaomi_ddv_df = xiaomi_ddv_df.query("id not in @values")

xiaomi_df = pd.concat([xiaomi_df, xiaomi_ddv_df])
xiaomi_df = xiaomi_df.reset_index(drop=True)
xiaomi_df['id'] = xiaomi_df.index
print(len(xiaomi_df))

80

## Matching data Oppo

## TGDD

In [39]:
oppo_df = oppo_tgdd_df
len(oppo_df)

2

## CellphoneS

In [40]:
oppo_matcher = fuzzymatcher.link_table(oppo_df, oppo_cps_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
oppo_matcher = oppo_matcher[oppo_matcher['match_score'] > 0.2]
oppo_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
2,12,5,0.359517,1,OPPO Reno7 Z 5G,OPPO Reno7 Z (5G),10490000,10490000,8,8,128.0,128.0,6.43,6.43

In [41]:
values = oppo_matcher['__id_right'].unique().tolist()
oppo_cps_df = oppo_cps_df.query("id not in @values")

oppo_df = pd.concat([oppo_df, oppo_cps_df])
oppo_df = oppo_df.reset_index(drop=True)
oppo_df['id'] = oppo_df.index
print(len(oppo_df))

21

## Viettel

In [42]:
oppo_matcher = fuzzymatcher.link_table(oppo_df, oppo_vt_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
oppo_matcher = oppo_matcher[oppo_matcher['match_score'] > 0.2]
oppo_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
1,1,30,0.231904,1,OPPO Reno7 Z 5G,OPPO Reno7 Z 5G,10490000,9990000,8,8,128.0,128.0,6.43,6.43

In [43]:
values = oppo_matcher['__id_right'].unique().tolist()
oppo_vt_df = oppo_vt_df.query("id not in @values")

oppo_df = pd.concat([oppo_df, oppo_vt_df])
oppo_df = oppo_df.reset_index(drop=True)
oppo_df['id'] = oppo_df.index
print(len(oppo_df))

30

## Tiki

In [44]:
oppo_matcher = fuzzymatcher.link_table(oppo_df, oppo_tiki_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
oppo_matcher = oppo_matcher[oppo_matcher['match_score'] > 0.2]
oppo_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
1,1,172,0.229514,1,OPPO Reno7 Z 5G,OPPO RENO7 Z 5G (8GB/128GB),10490000,9990000,8,8,128.0,128.0,6.43,6.43
2,2,225,0.229514,1,OPPO Reno6 Z 5G,Oppo Reno6 Z 5G (8GB/128GB),7390000,8289000,8,8,128.0,128.0,6.43,6.43
262,20,41,0.201006,1,OPPO A15s,Oppo A15s (4GB/64G),3790000,3790000,4,4,64.0,64.0,6.52,6.52
277,23,234,0.200681,1,OPPO A76,Oppo A76 6GB/128GB,5990000,5990000,6,6,128.0,128.0,6.56,6.56

In [45]:
values = oppo_matcher['__id_right'].unique().tolist()
oppo_tiki_df = oppo_tiki_df.query("id not in @values")

oppo_df = pd.concat([oppo_df, oppo_tiki_df])
oppo_df = oppo_df.reset_index(drop=True)
oppo_df['id'] = oppo_df.index
print(len(oppo_df))

60

## Didongviet

In [46]:
oppo_matcher = fuzzymatcher.link_table(oppo_df, oppo_ddv_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
oppo_matcher = oppo_matcher[oppo_matcher['match_score'] > 0.2]
oppo_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
11,5,49,0.216617,1,OPPO Reno6 5G,OPPO Reno6 5G (8GB|128GB),10290000,10290000,8,8.0,128.0,128.0,6.43,6.43
192,32,48,0.235673,1,Oppo Reno 5G (8GB/128G),OPPO Reno6 Z 5G (8GB|128GB),7290000,7290000,8,8.0,128.0,128.0,6.43,6.43
218,39,43,0.329066,1,Oppo A55 4GB/64GB,OPPO A55 (4GB|64GB),4069000,3990000,4,4.0,64.0,64.0,6.50,6.50
219,40,131,0.204232,1,OPPO RENO7 4G (8GB/128GB),OPPO Reno7 4G (8GB|128GB),8490000,7790000,8,8.0,256.0,0.0,6.40,6.40
233,42,40,0.360875,1,Oppo A16k 3GB/32GB,OPPO A16K (3GB|32GB),3290000,2890000,3,3.0,32.0,32.0,6.52,6.52
237,45,40,0.344971,1,OPPO A16K (3GB/32GB),OPPO A16K (3GB|32GB),2969000,2890000,3,3.0,32.0,32.0,6.52,6.52
238,46,116,0.270794,1,OPPO A76 (6GB/128GB),OPPO A76 (6GB|128GB),5385000,5090000,6,6.0,128.0,128.0,6.56,6.56
249,49,40,0.344971,1,Oppo A16K (3GB/32GB),OPPO A16K (3GB|32GB),3049000,2890000,3,3.0,32.0,32.0,6.52,6.52
262,51,43,0.424311,1,Oppo A55 (4GB/64GB),OPPO A55 (4GB|64GB),3970000,3990000,4,4.0,64.0,64.0,6.50,6.50
263,52,50,0.313863,1,OPPO A95 (8GB/128GB),OPPO A95 (8GB/128GB),5990000,5990000,8,8.0,128.0,128.0,6.43,6.43
264,53,43,0.344971,1,Oppo A55 (4GB/64GB),OPPO A55 (4GB|64GB),4490000,3990000,4,4.0,64.0,64.0,6.50,6.50
265,54,43,0.344971,1,OPPO A55 (4GB/64GB),OPPO A55 (4GB|64GB),4490000,3990000,4,4.0,64.0,64.0,6.50,6.50
278,56,40,0.355005,1,OPPO A16K (3GB/32GB),OPPO A16K (3GB|32GB),3190000,2890000,3,3.0,32.0,32.0,6.52,6.52

In [47]:
values = oppo_matcher['__id_right'].unique().tolist()
oppo_ddv_df = oppo_ddv_df.query("id not in @values")

oppo_df = pd.concat([oppo_df, oppo_ddv_df])
oppo_df = oppo_df.reset_index(drop=True)
oppo_df['id'] = oppo_df.index
print(len(oppo_df))

65

# Matching data other

## TGDD

In [48]:
other_df = other_tgdd_df
len(other_df)

11

## CellphoneS

In [49]:
other_matcher = fuzzymatcher.link_table(other_df, other_cps_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
other_matcher = other_matcher[other_matcher['match_score'] > 0.2]
other_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
0,14,159,0.209219,1,Vivo V23e,Vivo V21 5G,8490000,8500000,8,8,128.0,128.0,6.44,6.44
1,14,99,0.209040,2,Vivo V23e,Vivo V23e,8490000,7490000,8,8,128.0,128.0,6.44,6.44
16,22,188,0.244783,1,Realme C25Y 64GB,Realme C25Y 4GB 64GB,4690000,3790000,4,4,64.0,64.0,6.50,6.50
19,24,79,0.238506,1,Realme C35 64GB,Realme C35 4GB 64GB,4290000,3990000,4,4,64.0,64.0,6.60,6.60
23,26,96,0.250647,1,Vivo Y21,Vivo Y21,3990000,3600000,4,4,64.0,64.0,6.51,6.51
110,28,77,0.255911,1,Vivo Y15s,Vivo Y15s,3490000,2850000,3,3,32.0,32.0,6.51,6.51
114,32,55,0.289655,1,Realme C11 (2021),Realme C11 (2021),2990000,2490000,2,2,32.0,32.0,6.50,6.50
115,35,109,0.246657,1,Nokia 105 Single SIM,Nokia 105 (2019) 1 SM,480000,480000,0,0,0.0,0.0,1.77,1.77

In [50]:
values = other_matcher['__id_right'].unique().tolist()
other_cps_df = other_cps_df.query("id not in @values")

other_df = pd.concat([other_df, other_cps_df])
other_df = other_df.reset_index(drop=True)
other_df['id'] = other_df.index
print(len(other_df))

111

## Viettel

In [51]:
other_matcher = fuzzymatcher.link_table(other_df, other_vt_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
other_matcher = other_matcher[other_matcher['match_score'] > 0.2]
other_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
0,0,100,0.248892,1,Vivo V23e,Vivo V23e,8490000,6990000,8,8,128.000,128.000000,6.44,6.44
44,4,91,0.281286,1,Realme C35 64GB,Realme C35 (4/64GB),4290000,4290000,4,4,64.000,64.000000,6.60,6.58
45,5,78,0.247252,1,Vivo Y21,Vivo Y21,3990000,3790000,4,4,64.000,64.000000,6.51,6.51
86,7,31,0.229220,1,Vivo Y15s,Vivo Y15s,3490000,3090000,3,3,32.000,32.000000,6.51,6.51
770,28,106,0.331991,1,Vivo V23 5G,Vivo V23 5G,10990000,12490000,8,8,128.000,128.000000,6.44,6.44
1012,36,27,0.307466,1,Nokia C21 Plus 3GB 64GB,Nokia C21 Plus 3GB-64GB,2990000,2890000,3,3,64.000,64.000000,6.52,6.50
1014,38,113,0.284740,1,Nokia 110 4G,Nokia 110 4G,850000,850000,0,0,0.125,0.046875,1.80,1.80
1203,44,32,0.228824,1,Vivo Y33S,Vivo Y33s,5900000,5340000,8,8,128.000,128.000000,6.58,6.58
1253,47,43,0.349899,1,Vivo Y21S (4GB - 128GB),Vivo Y21s 4GB/128GB,4300000,4690000,4,4,128.000,128.000000,6.51,6.51
1374,51,114,0.274706,1,Nokia 105 4G,Nokia 105 4G,750000,750000,0,0,0.125,0.046875,1.80,1.80
1460,57,101,0.219140,1,Nokia C30,Nokia C30,2590000,2950000,3,3,32.000,32.000000,6.82,6.82
1705,67,90,0.307058,1,Nokia C21 Plus 3GB 32GB,Nokia C21 Plus 3GB-32GB,2790000,2690000,3,3,32.000,32.000000,6.52,6.50
1706,68,68,0.227531,1,Nokia 215 4G,Nokia 215 4G,829000,900000,0,0,0.125,0.125000,2.40,2.40
2136,82,82,0.387415,1,Realme C11 2021 4GB 64GB,Realme C11 2021 (4GB - 64GB),3190000,3490000,4,4,64.000,64.000000,6.50,6.50
2708,100,44,0.390036,1,Vivo Y21S (6GB - 128GB),Vivo Y21s 6GB/128GB,4650000,5190000,6,6,128.000,128.000000,6.51,6.51

In [52]:
values = other_matcher['__id_right'].unique().tolist()
other_vt_df = other_vt_df.query("id not in @values")

other_df = pd.concat([other_df, other_vt_df])
other_df = other_df.reset_index(drop=True)
other_df['id'] = other_df.index
print(len(other_df))

136

## Tiki

In [53]:
other_matcher = fuzzymatcher.link_table(other_df, other_tiki_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
other_matcher = other_matcher[other_matcher['match_score'] > 0.2]
other_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
77,4,236,0.234695,1,Realme C35 64GB,Realme C35 4GB/64GB,4290000,3899000,4,4,64.0,64.0,6.60,6.60
84,8,126,0.250279,1,Realme C21Y 3GB,Realme C21Y 3GB/32GB,3390000,2559000,3,3,32.0,32.0,6.50,6.50
480,16,4,0.299074,1,Tecno Spark 8C,TECNO Spark 8C (4GB/64GB),2650000,2648000,0,4,64.0,64.0,6.60,6.60
482,17,134,0.480977,1,Nubia Red Magic 6s Pro Cyborg 12GB 128GB,ZTE Nubia RedMagic 6s Pro Cyborg 12GB l 128GB,16490000,16290000,12,12,128.0,128.0,6.80,6.80
989,28,112,0.466208,1,Vivo V23 5G,Vivo V23 5G (8GB/128GB),10990000,10990000,8,8,128.0,128.0,6.44,6.44
1127,32,121,0.300199,1,Vsmart Joy 4,Vsmart Joy 4,3290000,3190000,3,0,64.0,64.0,6.50,6.53
1381,36,68,0.457669,1,Nokia C21 Plus 3GB 64GB,Nokia C21 Plus (3GB/64GB),2990000,2790000,3,3,64.0,64.0,6.52,6.52
1382,36,183,0.403774,2,Nokia C21 Plus 3GB 64GB,Nokia C21 Plus (2GB/64GB),2990000,2450000,3,3,64.0,64.0,6.52,6.52
1662,41,106,0.238316,1,Nokia C20 2GB 16GB,Nokia C20 (2GB/16GB),1790000,1680000,2,2,16.0,16.0,6.52,6.50
1663,41,213,0.238316,2,Nokia C20 2GB 16GB,Nokia C20 (2GB/16GB),1790000,1989000,2,2,16.0,16.0,6.52,6.50
1746,43,47,0.469610,1,Tecno Spark 7T 4GB 64GB,Tecno Spark 7T 4GB/64GB,2750000,2789000,4,4,64.0,64.0,6.52,6.52
1747,43,164,0.469610,2,Tecno Spark 7T 4GB 64GB,TECNO Spark 7T (4GB/64GB),2750000,2929000,4,4,64.0,64.0,6.52,6.52
2257,52,181,0.258316,1,Nokia G10,Nokia G10 (4GB/64GB),2990000,2990000,4,4,64.0,64.0,6.50,6.50
2678,62,199,0.266862,1,Realme 8 5G,Realme 8 5G,6790000,7490000,8,8,128.0,128.0,6.50,6.50
2822,67,63,0.455145,1,Nokia C21 Plus 3GB 32GB,Nokia C21 Plus (3GB/32GB),2790000,2590000,3,3,32.0,32.0,6.52,6.52
3109,72,201,0.205874,1,Realme 8 Pro,Realme 8 Pro (8GB/128GB),7590000,7990000,8,8,128.0,128.0,6.40,6.40
3593,82,108,0.333990,1,Realme C11 2021 4GB 64GB,Realme C11 2021 (4GB/64GB),3190000,3479000,4,4,64.0,64.0,6.50,6.50
3725,86,171,0.281169,1,Realme C21Y 4GB 64GB,Realme C21Y 4GB/64GB,3390000,3090000,4,4,64.0,64.0,6.50,6.50
3858,89,121,0.252332,1,Vsmart Joy 4 4GB,Vsmart Joy 4,3590000,3190000,4,0,64.0,64.0,6.50,6.53
4490,98,121,0.210171,1,Vsmart Joy 4 6GB,Vsmart Joy 4,3990000,3190000,6,0,64.0,64.0,6.50,6.53
4560,99,216,0.329973,1,Nokia C21 Plus 2GB 64GB,Nokia C21 Plus 2GB/64GB,2690000,2450000,2,2,64.0,64.0,6.52,6.50
4633,102,47,0.214380,1,Tecno Spark 7T 6GB 128GB,Tecno Spark 7T 4GB/64GB,3490000,2789000,6,4,128.0,64.0,6.52,6.52
5116,113,213,0.377987,1,Nokia C20 2GB-16GB,Nokia C20 (2GB/16GB),1990000,1989000,0,2,16.0,16.0,6.50,6.50
5117,113,106,0.248355,2,Nokia C20 2GB-16GB,Nokia C20 (2GB/16GB),1990000,1680000,0,2,16.0,16.0,6.50,6.50
5404,121,205,0.363040,1,Realme C11 2021 (2GB - 32GB),Realme C11 2021 (2GB/32GB),2590000,2439000,2,2,32.0,32.0,6.50,6.50
5405,121,159,0.353006,2,Realme C11 2021 (2GB - 32GB),Realme C11 2021 (2GB/32GB),2590000,2350000,2,2,32.0,32.0,6.50,6.50
5406,121,185,0.353006,3,Realme C11 2021 (2GB - 32GB),Realme C11 (2021)(2GB/32GB),2590000,2690000,2,2,32.0,32.0,6.50,6.50
5407,121,60,0.232865,4,Realme C11 2021 (2GB - 32GB),Realme C11 (2GB/32GB),2590000,2439000,2,2,32.0,32.0,6.50,6.50
5414,122,199,0.375213,1,Realme 8 5G,Realme 8 5G,7490000,7490000,0,8,128.0,128.0,6.50,6.50
6065,135,140,0.339790,1,ZTE Blade A31 Plus (2/32GB),ZTE Blade A31 Plus 2GB l 32GB,1990000,1890000,2,0,32.0,0.0,6.00,6.00

In [54]:
values = other_matcher['__id_right'].unique().tolist()
other_tiki_df = other_tiki_df.query("id not in @values")

other_df = pd.concat([other_df, other_tiki_df])
other_df = other_df.reset_index(drop=True)
other_df['id'] = other_df.index
print(len(other_df))

200

## Didongviet

In [55]:
other_matcher = fuzzymatcher.link_table(other_df, other_ddv_df, left_on, right_on, left_id_col = "id", right_id_col = "id")
other_matcher = other_matcher[other_matcher['match_score'] > 0.2]
other_matcher

,__id_left,__id_right,match_score,match_rank,ten_left,ten_right,gia_left,gia_right,ram_left,ram_right,bo_nho_trong_left,bo_nho_trong_right,kich_thuoc_man_hinh_left,kich_thuoc_man_hinh_right
960,24,69,0.330364,1,Nokia G21,Nokia G21 (4GB|128GB),3990000,3990000,4,4.000000,128.000,128.000,6.50,6.50
1846,46,68,0.303872,1,Nokia C30 2GB 32GB,Nokia C30 (3GB|32GB),2390000,3590000,2,3.000000,32.000,32.000,6.82,6.82
1883,47,59,0.537361,1,Vivo Y21S (4GB - 128GB),Vivo Y21s (4GB|128GB),4300000,4290000,4,4.000000,128.000,128.000,6.51,6.51
2022,51,67,0.299264,1,Nokia 105 4G,Nokia 105 4G,750000,670000,0,0.046875,0.125,0.125,1.80,1.80
4061,100,58,0.601440,1,Vivo Y21S (6GB - 128GB),Vivo Y21s (6GB|128GB),4650000,4650000,6,6.000000,128.000,128.000,6.51,6.51
5667,139,69,0.207346,1,Nokia G10 4GB/64GB,Nokia G21 (4GB|128GB),2890000,3990000,4,4.000000,64.000,128.000,6.50,6.50
6250,155,61,0.202182,1,Vivo Y15s (3GB/32GB) Hang Chinh Hang,Vivo Y15s (3GB|32GB),2790000,2750000,3,3.000000,32.000,32.000,6.50,6.51
6483,162,60,0.291509,1,Vivo Y21 4GB/64GB,Vivo Y21 (4GB|64GB),3679000,3490000,4,4.000000,64.000,64.000,6.50,6.51
6577,165,61,0.227908,1,Vivo Y12s 3GB/32GB,Vivo Y15s (3GB|32GB),3169000,2750000,3,3.000000,32.000,32.000,6.50,6.51
6762,170,69,0.466554,1,Nokia G21 4GB/128GB,Nokia G21 (4GB|128GB),3690000,3990000,4,4.000000,128.000,128.000,6.50,6.50
6855,173,60,0.212412,1,Vivo Y20 4GB/64GB,Vivo Y21 (4GB|64GB),3599000,3490000,4,4.000000,64.000,64.000,6.50,6.51
6949,176,55,0.214795,1,Nokia C21 Plus 2GB/32GB,Nokia C01 Plus (2GB|16GB),2389000,1420000,2,2.000000,32.000,16.000,6.50,5.45
7181,183,68,0.286843,1,Nokia C30 3GB/32GB,Nokia C30 (3GB|32GB),2890000,3590000,3,3.000000,32.000,32.000,6.81,6.82
7228,185,60,0.212412,1,Vivo Y15a (4GB/64GB),Vivo Y21 (4GB|64GB),2970000,3490000,4,4.000000,64.000,64.000,6.50,6.51
7371,191,68,0.270939,1,Nokia C30 (3GB/32GB),Nokia C30 (3GB|32GB),2959000,3590000,3,3.000000,32.000,32.000,6.81,6.82
7419,194,60,0.307413,1,Vivo Y21 (4GB/64GB),Vivo Y21 (4GB|64GB),3390000,3490000,4,4.000000,64.000,64.000,6.50,6.51
7421,195,60,0.233687,1,Vivo Y15A 4GB/64GB,Vivo Y21 (4GB|64GB),2990000,3490000,4,4.000000,64.000,64.000,6.50,6.51
7423,196,55,0.684595,1,Nokia C01 Plus 2GB/16GB,Nokia C01 Plus (2GB|16GB),1599000,1420000,2,2.000000,16.000,16.000,5.45,5.45
7424,197,61,0.307005,1,Vivo Y15s 3GB/32GB,Vivo Y15s (3GB|32GB),2819000,2750000,3,3.000000,32.000,32.000,6.50,6.51

In [56]:
values = other_matcher['__id_right'].unique().tolist()
other_ddv_df = other_ddv_df.query("id not in @values")

other_df = pd.concat([other_df, other_ddv_df])
other_df = other_df.reset_index(drop=True)
other_df['id'] = other_df.index
print(len(other_df))

238

## Merge all

In [57]:
df = pd.concat([apple_df, ss_df, xiaomi_df, oppo_df, other_df])
df = df.reset_index(drop=True)
print(len(df))

584

In [58]:
df = df.drop_duplicates(subset=['ten'])
print(len(df))

511

In [59]:
df.head()

,ten,gia,cong_nghe_man_hinh,cpu,ram,bo_nho_trong,sim,pin,kich_thuoc_man_hinh,id,src,thuong_hieu
0,iPhone 12 Pro 256GB,26290000,OLED,Apple A14 Bionic 6 nhân,6.0,256.0,1 Nano SIM & 1 eSIM,2815 mAh,6.1,0,Thế giới di động,apple
1,iPhone 12 64GB,19990000,OLED,Apple A14 Bionic 6 nhân,4.0,64.0,1 Nano SIM & 1 eSIM,2815 mAh,6.1,1,Thế giới di động,apple
2,iPhone 12 mini 64GB,18990000,OLED,Apple A14 Bionic 6 nhân,4.0,64.0,1 Nano SIM & 1 eSIM,2227 mAh,5.4,2,Thế giới di động,apple
3,iPhone SE 64GB (2020) (Hộp mới),9490000,IPS LCD,Apple A13 Bionic 6 nhân,3.0,64.0,1 Nano SIM & 1 eSIM,1821 mAh,4.7,3,Thế giới di động,apple
4,iPhone 11 64GB,11690000,IPS LCD,A13 Bionic,4.0,64.0,Nano-SIM + eSIM,3110 mAh,6.1,4,CellphoneS,apple

In [60]:
df.to_csv('clean_data/final_data.csv', index=False)
df.to_json('clean_data/final_data.json', orient="records")